@startuml DiagramName
start
:Text einlesen;
:Text normalisieren (exemple);
:Text in k-Gramme aufteilen;
:Rolling Hash auf k-Gramme anwenden;
:Winnowing: kleinste Hashes im Fenster auswählen(exemple);
:Fingerprints extrahieren(exemple);
:Vergleich der Fingerprints zweier Dokumente;
:Ähnlichkeitsanalyse durchführen;
stop
@enduml